import {
  BriefcaseIcon,
  DollarSignIcon,
  ShoppingBagIcon,
  CarIcon,
  ShieldCheckIcon,
  BookHeart,
  CreditCardIcon,
  FilmIcon,
  UtensilsIcon,
  Shirt,
  BookOpenIcon,
  ArrowUpCircleIcon,
  HammerIcon,
  DropletIcon,
  UserCheckIcon,
  ShoppingCartIcon,
  HomeIcon,
  BoltIcon,
} from "lucide-react";

export const incomeTypes = [
  { value: "Salary", icon: <BriefcaseIcon /> },
  { value: "Freelancing", icon: <DollarSignIcon /> },
  { value: "Investments", icon: <ArrowUpCircleIcon /> },
  { value: "Side Job", icon: <BriefcaseIcon /> },
  { value: "Gift", icon: <BookHeart /> },
  { value: "Rental Income", icon: <ShoppingBagIcon /> },
  { value: "Royalties", icon: <FilmIcon /> },
  { value: "Dividends", icon: <DollarSignIcon /> },
  { value: "Refunds", icon: <ShieldCheckIcon /> },
  { value: "Commissions", icon: <DollarSignIcon /> },
  { value: "Grants", icon: <DollarSignIcon /> },
  { value: "Alimony", icon: <BookHeart /> },
  { value: "Interest", icon: <DollarSignIcon /> },
  { value: "Capital Gains", icon: <ArrowUpCircleIcon /> },
  { value: "Selling Items", icon: <ShoppingCartIcon /> },
];

export const expenseTypes = [
  { value: "Rent/Mortgage", icon: <HomeIcon /> },
  { value: "Utilities", icon: <BoltIcon /> },
  { value: "Groceries", icon: <ShoppingCartIcon /> },
  { value: "Transportation", icon: <CarIcon /> },
  { value: "Insurance", icon: <ShieldCheckIcon /> },
  { value: "Healthcare/Medical", icon: <BookHeart /> },
  { value: "Debt Payments", icon: <CreditCardIcon /> },
  { value: "Entertainment", icon: <FilmIcon /> },
  { value: "Dining Out", icon: <UtensilsIcon /> },
  { value: "Clothing", icon: <Shirt /> },
  { value: "Education", icon: <BookOpenIcon /> },
  { value: "Savings/Investments", icon: <ArrowUpCircleIcon /> },
  { value: "Home Maintenance", icon: <HammerIcon /> },
  { value: "Personal Care", icon: <DropletIcon /> },
  { value: "Subscriptions/Memberships", icon: <UserCheckIcon /> },
];
